# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
